#ifndef _FLEXLANG_TYPES_H
#define _FLEXLANG_TYPES_H
#include <stdio.h>
#include <stdlib.h>

enum flextoken_types {
	// TOKEN IDENTIFIERS FOR KEYWORDS
	FLEXTOKEN,
	FLEXTOKEN_INPUT,
	FLEXTOKEN_WRITE,
	FLEXTOKEN_INT,
	FLEXTOKEN_STRING,
	FLEXTOKEN_FLOAT,
	FLEXTOKEN_BOOL,
	FLEXTOKEN_WORD,
	FLEXTOKEN_RETURN,

	// TOKEN IDENTIFIER FOR SPACE
	FLEXTOKEN_SPACE,

	// TOKEN IDENTIFIERS FOR PUNCTUAION
	FLEXTOKEN_SINGLEQUOTE,
	FLEXTOKEN_DOUBLEQUOTE,
	FLEXTOKEN_OPENCURLYBRACE,
	FLEXTOKEN_CLOSEDCURLYBRACE,
	FLEXTOKEN_OPENCURVEDBRACE,
	FLEXTOKEN_CLOSEDCURVEDBRACE,
	FLEXTOKEN_COLON,
	FLEXTOKEN_SEMICOLON,

	// TOKEN IDENTIFIERS FOR MATHEMATICAL, BITWISE, ASSIGNMENT, AND COMPARISON OPERATORS (PUNCUTATION)
	FLEXTOKEN_ADD,
	FLEXTOKEN_SUB,
	FLEXTOKEN_MULT,
	FLEXTOKEN_DIV,
	FLEXTOKEN_AND,
	FLEXTOKEN_OR,
	FLEXTOKEN_XOR,
	FLEXTOKEN_EQUAL,
	FLEXTOKEN_LESSTHAN,
	FLEXTOKEN_GREATERTHAN,

	// TOKEN IDENTIFIER FOR OTHER PUNCTUATIONS
	FLEXTOKEN_PUNCTUATION
};

static const char* flextoken_idnames[] = {
	// TOKEN IDENTIFIERS FOR KEYWORDS
	"FLEXTOKEN",
	"FLEXTOKEN_INPUT",
	"FLEXTOKEN_WRITE",
	"FLEXTOKEN_INT",
	"FLEXTOKEN_STRING",
	"FLEXTOKEN_FLOAT",
	"FLEXTOKEN_BOOL",
	"FLEXTOKEN_WORD",
	"FLEXTOKEN_RETURN",

	// TOKEN IDENTIFIER FOR SPACE
	"FLEXTOKEN_SPACE",
	
	// TOKEN IDENTIFIERS FOR PUNCTUATION
	"FLEXTOKEN_SINGLEQUOTE",
	"FLEXTOKEN_DOUBLEQUOTE",
	"FLEXTOKEN_OPENCURLYBRACE",
	"FLEXTOKEN_CLOSEDCURLYBRACE",
	"FLEXTOKEN_OPENCURVEDBRACE",
	"FLEXTOKEN_CLOSEDCURVEDBRACE",
	"FLEXTOKEN_COLON",
	"FLEXTOKEN_SEMICOLON",

	// TOKEN IDENTIFIERS FOR OPERATORS (PUNCTUATION)
	"FLEXTOKEN_ADD",
	"FLEXTOKEN_SUB",
	"FLEXTOKEN_MULT",
	"FLEXTOKEN_DIV",
	"FLEXTOKEN_AND",
	"FLEXTOKEN_OR",
	"FLEXTOKEN_XOR",
	"FLEXTOKEN_EQUAL",
	"FLEXTOKEN_LESSTHAN",
	"FLEXTOKEN_GREATERTHAN",

	// TOKEN IDENTIFIER FOR OTHER PUNCTUATIONS
	"FLEXTOKEN_PUNCTUATION"
};
#endif
